groups:
  - name: APM Alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(node_cpu_seconds_total{mode!="idle"}[5m]) > 0.8
        for: 1m
        labels:
          severity: "critical"
        annotations:
          description: "CPU usage is over 80% for the last 5 minutes."

      - alert: HighMemoryUsage
        expr: node_memory_Active_bytes / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: "critical"
        annotations:
          description: "Memory usage is above 90% for the last 5 minutes."

      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          description: "PostgreSQL service is down."

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          description: "Redis service is down."

      - alert: HighLatency
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 1.0
        for: 5m
        labels:
          severity: "critical"
        annotations:
          description: "Request latency is over 1 second for the last 5 minutes."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status!~'2..'}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: "critical"
        annotations:
          description: "Error rate is above 5% for the last 5 minutes."

      - alert: LowApdexScore
        expr: apdex(http_request_duration_seconds) < 0.8
        for: 5m
        labels:
          severity: "critical"
        annotations:
          description: "Apdex score is below 0.8 for the last 5 minutes."
