global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rails_app'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['localhost:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
