groups:
  - name: APM Alerts
    rules:
      - alert: HighLatency
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 1.0
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "99th percentile of request latency is higher than 1 second."

      - alert: HighTraffic
        expr: rate(http_request_total[5m]) > 1000
        for: 1m
        labels:
          severity: warning
        annotations:
          description: "High traffic - over 1000 requests per minute."

      - alert: HighErrorRate
        expr: rate(http_errors_total[5m]) / rate(http_request_total[5m]) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "More than 5% of requests are failing."

      - alert: HighSaturation
        expr: node_cpu_seconds_total{mode!="idle"} > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "CPU saturation is over 90%."

      - alert: LowApdexScore
        expr: (rate(http_apdex_satisfied[5m]) + (rate(http_apdex_tolerating[5m]) / 2)) / rate(http_request_total[5m]) < 0.85
        for: 1m
        labels:
          severity: warning
        annotations:
          description: "Apdex score is below 0.85."
      - alert: HighCPUUsage
        expr: rate(node_cpu_seconds_total{mode!="idle"}[5m]) > 0.8
        for: 1m
        labels:
          severity: "critical"
        annotations:
          description: "CPU usage is over 80% for the last 5 minutes."

      - alert: HighMemoryUsage
        expr: node_memory_Active_bytes / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: "critical"
        annotations:
          description: "Memory usage is above 90% for the last 5 minutes."

      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          description: "PostgreSQL service is down."

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          description: "Redis service is down."
